### ISSUE TITLE
Document SAMM ranking

### ISSUE THREAD

**Issue by matsen** [matsengrp/samm#298]
The SAMM ranking is doing rather well in @krdav's phylogenetics bake-off. Could someone please add some documentation about how that script is used?

**Comment by matsen** [comment]
I believe this was done in https://github.com/matsengrp/samm/commit/4c513b69ba47227062cc8f9c2a92522e81e77ba9 👍 . Could someone cut a new release (v0.2?) and close this issue?

**Comment by dawahs** [comment]
Closed via #299
